apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: app-todo
    annotations:  #tells the NGINX Ingress Controller to rewrite the request path before it forwards the request to your backend service
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
      nginx.ingress.kubernetes.io/proxy-buffers: "16 16k"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "24k"
      nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - secretName: mkcert-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-web-ui
                port:
                  number: 8080
