name: Build and Push Web API Image

on:
  workflow_dispatch: # manual trigger

env:
  IMAGE_NAME: todo-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version file
        run: |
          base_version=$(cat .version)
          new_version="${base_version}.${{ github.run_number }}"
          echo "$new_version" > .version
          echo "VERSION=$new_version" >> $GITHUB_ENV
          echo "Version updated to $new_version"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/apps/App.Api.Todo/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ env.VERSION }}

      - name: Logout
        run: docker logout
